### ISSUE TITLE
Multiple subscription collectors running at the same time

### ISSUE THREAD

**Issue by DavisPoGo** [PartTimeJS/WDR#32]
The easiest way to describe this issue is with an example:
Lets say I enter `.pokemon` and then `view`
Then `.raid` and `add`
At this point, I get prompts for adding both a pokemon and raid subscription.

My assumption would be that by entering `.raid`, the `.pokemon` series of prompts would end and the `.raid` series of prompts would begin. Instead they both seem to be operating simultaneously. This happens with all the subscription commands (not just raid and pokemon) and you can get more than two collectors going at once. Please let me know if this is not clear enough of a description of the problem.

Here are the two different errors that pop up in the log:
`0|WDR  | DiscordAPIError: Unknown Message
0|WDR  |     at RequestHandler.execute (/home/cvm/WDR/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
0|WDR  |     at runMicrotasks (<anonymous>)
0|WDR  |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
0|WDR  |   method: 'delete',
0|WDR  |   path: '/channels/XXXXXXXXXXXX/messages/XXXXXXXXXXX',
0|WDR  |   code: 10008,
0|WDR  |   httpStatus: 404
` 

`0|WDR  | TypeError: Cannot read property 'channel' of null
0|WDR  |     at /home/cvm/WDR/src/commands/subscription/raid/collect_match.js:8:35
0|WDR  |     at new Promise (<anonymous>)
0|WDR  |     at Object.module.exports [as MatchCollect] (/home/cvm/WDR/src/commands/subscription/raid/collect_match.js:3:12)
0|WDR  |     at Query.onResult (/home/cvm/WDR/src/commands/subscription/raid/create.js:78:55)
0|WDR  |     at runMicrotasks (<anonymous>)
0|WDR  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

**Comment by DavisPoGo** [comment]
I think I figured out how to fix this. I'll submit a PR soon
