### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Crippe83** [PartTimeJS/WDR#9]
Latest master and when I now reload it gives me this;
```0|wdr  | 2020-05-06T01:26:50: (node:31626) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
0|wdr  | 2020-05-06T01:26:50:     at DiscordEmojis.LoadEmojis [as Load] (/root/bots/wdr_wip/modules/base/emojis.js:179:38)
0|wdr  | 2020-05-06T01:26:50:     at Client.MAIN.on (/root/bots/wdr_wip/modules/base/bot.js:600:15)
0|wdr  | 2020-05-06T01:26:50:     at Client.emit (events.js:198:15)
0|wdr  | 2020-05-06T01:26:50:     at WebSocketConnection.triggerReady (/root/bots/wdr_wip/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
0|wdr  | 2020-05-06T01:26:50:     at WebSocketConnection.checkIfReady (/root/bots/wdr_wip/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
0|wdr  | 2020-05-06T01:26:50:     at GuildCreateHandler.handle (/root/bots/wdr_wip/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
0|wdr  | 2020-05-06T01:26:50:     at WebSocketPacketManager.handle (/root/bots/wdr_wip/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
0|wdr  | 2020-05-06T01:26:50:     at WebSocketConnection.onPacket (/root/bots/wdr_wip/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
0|wdr  | 2020-05-06T01:26:50:     at WebSocketConnection.onMessage (/root/bots/wdr_wip/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
0|wdr  | 2020-05-06T01:26:50:     at WebSocket.onMessage (/root/bots/wdr_wip/node_modules/ws/lib/event-target.js:120:16)
0|wdr  | 2020-05-06T01:26:50: (node:31626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|wdr  | 2020-05-06T01:26:50: (node:31626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

modules/base/emojis.js:179:38:
`let guild = bot.guilds.cache.get(guildArray[i][0]);`

It was running fine before this, I pulled a couple of days ago.
Is there another emoji server, or is it something else I need to do?

**Comment by Crippe83** [comment]
I rolled back to Tile logging commit 311f749e3c3989d656e10a13e96df7d3384708cc which seem to be still working

**Comment by PartTimeJS** [comment]
You need to update your discord.js with npm to 12.2

**Comment by PartTimeJS** [comment]
npm uninstall discord.js
npm install discord.js@12.2
